version: '3.9'

services:
  test-task-db:
    security_opt:
      - label:disable
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

  test-task-server:
    # for SELinux
    security_opt:
      - label:disable
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    # volumes:
    #   - .:/usr/src/app
    depends_on:
      - test-task-db

volumes:
  postgres-db: